### ISSUE TITLE
Request - support Tags based on suffix or prefix

### ISSUE THREAD

**Issue by Wolfgang-IX** [InfinityCg/colorspacer#3]
Hi, often time I work with textures that has specific suffix without separator.
for example
- Albedo (A): textures**A**
- Materiality (M): textures**M** 
 (channel packed textures, contains various maps like roughness, metallic, AO, alpha and mask)
- Normal (N): textures**N**

and add an option to specify how many characters to look for, on the example above it would be the last single character (A,M,N).

Thanks 😄

**Comment by InfinityCg** [comment]
Hi @Wolfgang-IX 
Thank you for the feature request, I appreciate the feedback and the support towards the addon.

It would certainly be useful to add a feature like Prefix or suffix search and would make it easier to assign the colorspace in specific use cases
However, I am currently working on the other features and the current priority is making the node based engine better and provide quality of life improvements for the users, 
I will keep the suggestion in mind when I work on the text based engine, Please look forward to the future updates

Thank you for the support,
Yours sincerely,
InfinityCg

**Comment by Wolfgang-IX** [comment]
i figured it out a while ago, so you can add . after the suffix you want, works in my case.

![blender_XvTBwhKkKF](https://github.com/InfinityCg/colorspacer/assets/47208316/36e83441-91e5-40e3-941e-e146fe76c35f)
