### ISSUE TITLE
UV map assignment 

### ISSUE THREAD

**Issue by speaker-60** [InfinityCg/colorspacer#4]
Similar thing to this but to auto assign a uvmap node set to an assigned uvset based on on texture keywords

I have some _l and _o textures that use a second uv set to the main set of textures, having to go in add the uvmap node al a big scene with lots of meshes is a pain so a addon like this to automate that would be excellent

**Comment by InfinityCg** [comment]
Yeah, it will work, just change the assignment to a node group with defined params, you could check the code of the release and see if it works for you
