### ISSUE TITLE
cg-config-v2.2.0_aces-v1.3_ocio-v2.3

### ISSUE THREAD

**Issue by smitone** [InfinityCg/colorspacer#5]
Hello, thank you very much for your addon. I am encountering the following error: I am using the version cg-config-v2.2.0_aces-v1.3_ocio-v2.3 for ACES, and it shows this error. Is it possible to add the nomenclatures used by this file, or am I doing something wrong?

![image](https://github.com/user-attachments/assets/31effa0d-56be-4b39-b049-a1960bdbdc94)

Python: Traceback (most recent call last):
  File "C:\Users\rpobl\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\color_spacer\__init__.py", line 318, in invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rpobl\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\color_spacer\__init__.py", line 251, in execute
    bpy.data.images[image_name].colorspace_settings.name = supported_nodes[node.type]['actions'][input_name]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: bpy_struct: item.attr = val: enum "Utility - sRGB - Texture" not found in ('ACES2065-1', 'ACEScc', 'ACEScct', 'ACEScg', 'Display P3 - Display', 'Gamma 1.8 Encoded Rec.709', 'Gamma 2.2 Encoded AdobeRGB', 'Gamma 2.2 Encoded AP1', 'Gamma 2.2 Encoded Rec.709', 'Gamma 2.4 Encoded Rec.709', 'Linear AdobeRGB', 'Linear P3-D65', 'Linear Rec.2020', 'Linear Rec.709 (sRGB)', 'P3-D65 - Display', 'Raw', 'Rec.1886 Rec.709 - Display', 'Rec.2100-PQ - Display', 'sRGB - Display', 'sRGB Encoded AP1', 'sRGB Encoded P3-D65', 'sRGB Encoded Rec.709 (sRGB)', 'ST2084-P3-D65 - Display')

**Comment by InfinityCg** [comment]
Hi, It looks like you are trying to set the value to Utility - sRGB texture
but it is not provided with the configuration.
There are two possible solutions
1) You could try a different ACES config, (
https://www.youtube.com/watch?v=aw1xjChY_9U) This one has all the options
that you might need for an ACES workflow
2) I will try updating the add-on to add that particular role (It could
take me a little while)

What I'd advise is that you download the config according to the video and
see if it works for you, and send me a list of color-roles that you need
and classify them as "Color, Non-color etc.", I will add them all at once
for a general release and update the add-on in a few days

Please let me know if that works for you.
Thanks and Regards.

**Comment by smitone** [comment]
Thank you very much for your quick reply. Yes, it works with that file, but it is based on an older version, and my workflow in DaVinci uses ACES 1.3. From what I’ve read, there have been several changes in the role names. Based on what I was able to test, it should be set up as follows:

Color: sRGB Encoded Rec.709
Non-Color: Raw
Custom 1: Linear Rec.709

For Custom 2, I’m not entirely sure what should go here; I suppose it could be ACEScg or ACEScct, but I’m not very clear about this part.

**Comment by InfinityCg** [comment]
No worries, Please provide a link to the config file and I shall make the
necessary changes to the addon. Although I will try to update it as soon as
possible, it will still take me a few days at-least

Custom is just for the tag based search, in that, you can assign tags that
your images might have (AO, base etc.) and then it will assign the roles
accordingly. So each of the four columns could be anything
I have just preset the base, Albedo etc. to Color, Normal and the similar
to Non-color and left custom columns empty, you can change them in the
addon settings

**Comment by smitone** [comment]
https://github.com/AcademySoftwareFoundation/OpenColorIO-Config-ACES/releases This is the Git with all Config and the lastest working with blender is the 2.3 (2.4 don´t work) https://github.com/AcademySoftwareFoundation/OpenColorIO-Config-ACES/releases/download/v2.1.0-v2.2.0/cg-config-v2.2.0_aces-v1.3_ocio-v2.3.ocio

no problem, I can wait, and again, thank you for your work.

**Comment by InfinityCg** [comment]
Thanks a lot for your patience and for the links, I will implement the changes as soon as possible and let you know.

**Comment by InfinityCg** [comment]
> https://github.com/AcademySoftwareFoundation/OpenColorIO-Config-ACES/releases This is the Git with all Config and the lastest working with blender is the 2.3 (2.4 don´t work) https://github.com/AcademySoftwareFoundation/OpenColorIO-Config-ACES/releases/download/v2.1.0-v2.2.0/cg-config-v2.2.0_aces-v1.3_ocio-v2.3.ocio
> 
> no problem, I can wait, and again, thank you for your work.

Hi, I have added a test build to blendermarket and Gumroad, Please update the addon and see if it work for you. Let me know if there are errors

**Comment by smitone** [comment]
![image](https://github.com/user-attachments/assets/b2af1478-d9da-4f57-8dfa-ccd028306115)
It's working!!! Thank you so much... I just have a suggestion that was partly my mistake. There are some HDRIs that work better with ACEScg. Could you add that option? That way, we could choose between Linear Rec.709 or ACEScg.

**Comment by InfinityCg** [comment]
No worries!, I am updating the addon further to include an option to change
HDRI independently, and will include these options in it.
Please let me know if that works for you.
Thanks

**Comment by InfinityCg** [comment]
The addon has been updated, please download the latest version from Blendermarket/Gumroad. I hope this solves all the issues, please let me know if it doesn't.
Thanks
